version: "3"
services:
  frontend:
    
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - IMAGE_TAG=latest

    stdin_open: true

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - IMAGE_TAG=latest

    
  nginx:
      restart: always
      build:
        dockerfile: Dockerfile
        args:
        - IMAGE_TAG=latest
        context: ./nginx
      ports:  
        - 2000:80