version: "3"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - mynetwork

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - mynetwork

  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
      
    ports:
      - 2000:80
    networks:
      - mynetwork

networks:
  mynetwork: