version: "3"
services:
  frontend:
    
    build:
      context: ./frontend
      dockerfile: Dockerfile
    stdin_open: true

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    
  nginx:
      restart: always
      build:
        dockerfile: Dockerfile
        context: ./nginx
      ports:  
        - 2000:80