version: "3"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - mynetwork

  backend:
    environment:
      - DATABASE_URL="mongodb+srv://yxfSjjvpeVGuThMc:yxfSjjvpeVGuThMc@boilerplate.k53ydje.mongodb.net/?retryWrites=true&w=majority"
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - mynetwork

  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
      
    ports:
      - 2000:80
    networks:
      - mynetwork

networks:
  mynetwork: