name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ADMIN_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_ADMIN_SECRET_ACCESS_KEY}}
          aws-region: ${{ secrets.AWS_ADMIN_REGION}}


      - name: Install and configure AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
          aws configure set default.region ${{ secrets.AWS_ADMIN_REGION}}
          
      - name: Build and tag and push images to Docker Hub
        run: |
          docker login --username jeong5575 --password ${{ env.DOCKER_PASSWORD }}
          docker compose build
          docker tag boiler-plate-frontend jeong5575 / boiler-plate-frontend:latest
          docker tag boiler-plate-backend jeong5575 / boiler-plate-backend:latest
          docker tag boiler-plate-nginx jeong5575 / boiler-plate-nginx:latest
          docker push jeong5575/boiler-plate-frontend:latest
          docker push jeong5575/boiler-plate-backend:latest
          docker push jeong5575/boiler-plate-nginx:latest

          
      # - name: Login to Amazon ECR Public
      #   run: |
      #     echo "${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
      #     echo "${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
      #     aws configure set region us-east-1
      #     AWS_ECR_PASSWORD=$(aws ecr-public get-login-password --region us-east-1)
      #     echo $AWS_ECR_PASSWORD | docker login --username AWS --password-stdin public.ecr.aws/yuseok-web

     
      # - name: Connect to EC2 instance and deploy
      #   run: |
      #     ssh -i <path-to-ssh-private-key> <ec2-user>@<ec2-instance-ip> "sudo docker-compose -f <path-to-docker-compose-file> up -d"