name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ADMIN_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_ADMIN_SECRET_ACCESS_KEY}}
          aws-region: ${{ secrets.AWS_ADMIN_REGION}}

      - name: Install and configure AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
          aws configure set default.region ${{ secrets.AWS_ADMIN_REGION}}

      - name: Build and tag Docker images
        run: |
          docker-compose build

      - name: Login to Amazon ECR Public
        run: |
          aws ecr-public get-login-password --region us-east-1 
          docker login --username AWS --password-stdin public.ecr.aws

      - name: Build, tag, and push docker image to Amazon ECR Public
        env:
          REGISTRY: public
          REGISTRY_ALIAS: yuseok-web 
          REPOSITORY: yuseok-web 
          IMAGE_TAG: composed-docker
        run: |
          docker build -t $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG

      # - name: Connect to EC2 instance and deploy
      #   run: |
      #     ssh -i <path-to-ssh-private-key> <ec2-user>@<ec2-instance-ip> "sudo docker-compose -f <path-to-docker-compose-file> up -d"